# Generated by Django 2.1.7 on 2020-04-04 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsapp', '0006_auto_20190408_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='rank',
            field=models.IntegerField(default=0),
        ),
    ]
